// <auto-generated />
namespace VooDiDb.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AudienceColumns_changed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AudienceColumns_changed));
        
        string IMigrationMetadata.Id
        {
            get { return "201803210831407_AudienceColumns_changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
